language: php

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-add .travis/php.ini
  - composer self-update
  - composer require --dev

install:
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml.travis
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run --config-file ./.php_cs

after_script:
  - ./vendor/bin/phpcov merge --clover .reports/clover.xml .reports/coverage
  - ./vendor/bin/coveralls -v --config .coveralls.yml

services:
  - rabbitmq

notifications:
  email:
  - and-rey2@yandex.ru
